services:
  # Web Service (Frontend + Backend)
  - type: web
    name: ccl-app
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ccl-database
          property: connectionString
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true

      # --- AI integration ---
      - key: OPENAI_API_KEY
        value: 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
      - key: CCL_API_KEY
        sync: API_KEY
      - key: FLEXPATH_API_KEY
        sync: API_KEY

databases:
  - name: ccl-database
    databaseName: ccl_production
    user: ccl_user
    plan: starter