services:
  # Web Service (Frontend + Backend)
  - type: web
    name: ccl-app
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ccl-database
          property: connectionString
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: CCL_API_KEY
        sync: API_KEY
      - key: FLEXPATH_API_KEY
        sync: API_KEY
    
# PostgreSQL Database
databases:
  - name: ccl-database
    databaseName: ccl_production
    user: ccl_user
    plan: starter

# Optional: Static Site for docs
# - type: static_site
#   name: ccl-docs
#   buildCommand: npm run build:docs
#   publishPath: ./docs/dist