services:
  # CCL Agent System - Lean & Mean Architecture
  - type: web
    name: ccl-agent-system
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: ccl-database
          property: connectionString
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: CCL_API_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        fromSecretKey: OPENAI_API_KEY
      - key: OPENROUTER_API_KEY
        fromSecretKey: OPENROUTER_API_KEY
      # Deployment Configuration
      - key: RENDER_DEPLOYMENT
        value: true
      - key: GRACEFUL_STARTUP
        value: true
      - key: SERVICE_TIMEOUT_MS
        value: 10000
      - key: DB_CONNECTION_TIMEOUT_MS
        value: 5000
      - key: MAX_STARTUP_RETRIES
        value: 3
      # Neon WebSocket Configuration
      - key: NEON_WEBSOCKET_PROXY
        value: false

databases:
  - name: ccl-database
    databaseName: ccl_production
    user: ccl_user